project_id: '620320'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  # JSON 翻译文件
  - source: /public/locales/zh-CN/**/*
    translation: /public/locales/%locale%/**/%original_file_name%