# 支持灰度发布,使用istio-gateway实现流量控制
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.project }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.istio.hosts }}
        - {{ . | quote }}
        {{- end }}

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.project }}
spec:
  hosts:
    {{- range .Values.istio.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ .Values.project }}-gateway
  http:
    {{- if .Values.istio.canary.enabled }}
    - match:
        {{- toYaml .Values.istio.canary.match | nindent 8 }}
      route:
        - destination:
            host: {{ .Values.project }}-canary-scriptcat-list-frontend
    - match:
        {{- toYaml .Values.istio.match | nindent 8 }}
      route:
        - destination:
            host: {{ .Values.project }}-scriptcat-list-frontend
    {{ else }}
    - match:
        {{- toYaml .Values.istio.match | nindent 8 }}
      route:
        - destination:
            host: {{ .Values.project }}-scriptcat-list-frontend
    {{ end }}
